### ISSUE TITLE
Bump formula to latest version 3.2.0

### ISSUE THREAD

**Issue by infotexture** [crowdin/homebrew-crowdin#5]
I installed the Crowdin CLI via the instructions at https://support.crowdin.com/cli-tool/#installation, which installs v3.1.15 per 
https://github.com/crowdin/homebrew-crowdin/blob/32f61f45fcee28f8a6a8af7ff781f34806309cbb/Formula/crowdin%403.rb#L6

However, whenever I run the command, I'm prompted to upgrade to a newer version:

```bash
┌────────────────────────────────────────────────────────────┐
│  New version of Crowdin CLI is available! 3.1.15 -> 3.2.0  │
│             Please update for best experience!             │
└────────────────────────────────────────────────────────────┘
```

💡 If you'd like people to update, it would be nice to maintain the formula along with the message.

— So whenever people run `brew tap crowdin/crowdin` & `brew install crowdin@3`, they automatically get the latest version.

**Comment by infotexture** [comment]
While you're at it, you might want to automate your release process, so whenever a new version of the CLI tool is released, a pull request is created to update the formula accordingly.

**Comment by andrii-bodnar** [comment]
Hi @infotexture, thanks for the suggestions, just updated the formula. 

We are definitely going to automate this process.

**Comment by infotexture** [comment]
🙏 Thanks @andrii-bodnar — fastest fix ever, nice!
