### ISSUE TITLE
Calling depends_on :java is deprecated

### ISSUE THREAD

**Issue by infotexture** [crowdin/homebrew-crowdin#6]
When I ran `brew update` today, I got the following error message:

```shell
Warning: Calling depends_on :java is deprecated! Use "depends_on "openjdk@11", 
"depends_on "openjdk@8" or "depends_on "openjdk" instead.

Please report this issue to the crowdin/crowdin tap (not Homebrew/brew or 
Homebrew/core), or even better, submit a PR to fix it:

  /usr/local/Homebrew/Library/Taps/crowdin/homebrew-crowdin/Formula/crowdin@3.rb:12
```

Not sure how you'd like to handle this, so I'm filing this as an issue instead of creating a PR directly, but it looks like the `java` reference here should be updated with one of the `openjdk` proposals above:

https://github.com/crowdin/homebrew-crowdin/blob/master/Formula/crowdin%403.rb#L12

**Comment by Natalia936** [comment]
Hello, we're sorry to hear that, our tech guys will take a look into that and update you once there are some news

**Comment by andrii-bodnar** [comment]
Hi @infotexture!

Just released a new version of CLI and fixed this deprecated statement in the Formula.

Could you please check if everything is ok now?

**Comment by infotexture** [comment]
@andrii-bodnar ✅ The changes for Version 3.5.0 in https://github.com/crowdin/homebrew-crowdin/pull/7 fix this issue for `crowdin@3`, thanks. 🙏 

(The same issue remains for `crowdin@2.rb:11`, but I'm not sure if you're still maintaining that previous version.)
